import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Todos from '../components/Todos'
import styles from '../styles/Home.module.css'
import TodoForm from '../components/TodoForm'
import {useDispatch, useSelector} from 'react-redux'
import {useEffect} from 'react'
import {RootState} from '../redux/index'


const Home= () => {  

  const todos = useSelector((state: RootState) =>state.todos.allTodos) 
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <h1 style={{color: '#ff8898'}}>ToDos</h1>
        <TodoForm />
        <Todos 
            todos={todos}
             />
      </main>    
    </div>
  )
}

export default Home


