import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useDispatch, useSelector} from 'react-redux'
import {useEffect} from 'react'
import {RootState} from '../redux/index'
import Header from '../components/Header'
import TodoList from '../components/TodoList'
import Footer from '../components/Footer'


const Home= () => {  

  const todos = useSelector((state: RootState) =>state.todos.allTodos) 
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <Header />
        <TodoList todos={todos} />
        <Footer />
       
      </main>    
    </div>
  )
}

export default Home


